name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
env:
  IMAGE_NAME_API: api
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    
    - uses: actions/checkout@v3
             
    - name: Build the Api Docker image
      run: docker build . --file src/Promotions.Server/WebApi/Dockerfile --tag $IMAGE_NAME_API

    - name: Push Api image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME_API

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        docker tag $IMAGE_NAME_API $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
